# Generated by Django 5.2.6 on 2025-09-21 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashpromo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.product'),
        ),
        migrations.AddField(
            model_name='productreservation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.product'),
        ),
    ]
