# Generated by Django 5.2.6 on 2025-09-21 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='flashpromo',
            index=models.Index(fields=['is_active', 'start_time', 'end_time'], name='promotions__is_acti_cf712a_idx'),
        ),
        migrations.AddIndex(
            model_name='productreservation',
            index=models.Index(fields=['reserved_until', 'is_completed'], name='promotions__reserve_3b85ad_idx'),
        ),
    ]
